
{{- if and .Values.persistence.downloads.enabled (not .Values.persistence.downloads.existingClaim) }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "common.names.fullname" . }}-downloads
  labels:
    {{- include "common.labels" . | nindent 4 }}
spec:
  accessModes:
    - {{ .Values.persistence.downloads.accessMode | quote }}
  resources:
    requests:
      storage: {{ .Values.persistence.downloads.size | quote }}
  {{- if .Values.persistence.downloads.storageClass }}
  {{- if (eq "-" .Values.persistence.downloads.storageClass) }}
  storageClassName: ""
  {{- else }}
  storageClassName: {{ .Values.persistence.downloads.storageClass | quote }}
  {{- end }}
  {{- end }}
{{- end }}
